SELECT partida from partidasIngresos;

select * from PARTIDAS_EGRESOS;

.tables

PRAGMA table_info(PARTIDAS_EGRESOS);


SELECT "CLAVE CUCoP", COUNT(*) AS cantidad
FROM PARTIDAS_EGRESOS
GROUP BY "CLAVE CUCoP"
HAVING COUNT(*) > 1;


SELECT *
FROM PARTIDAS_EGRESOS
WHERE "CLAVE CUCoP" IS NULL;


SELECT *
FROM PARTIDAS_EGRESOS
WHERE "CLAVE CUCoP" IN (
    SELECT "CLAVE CUCoP"
    FROM PARTIDAS_EGRESOS
    WHERE "CLAVE CUCoP" IS NOT NULL
    GROUP BY "CLAVE CUCoP"
    HAVING COUNT(*) > 1
);



